In [1]:
import torch
import numpy as np

In [5]:
t = np.array([0, 1, 2, 3, 4, 5, 6])

In [6]:
print(t)

[0 1 2 3 4 5 6]


In [7]:
t.ndim

1

In [8]:
t.shape

(7,)

In [9]:
t[2:5]

array([2, 3, 4])

In [3]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [11]:
t.ndim

2

In [12]:
t.shape

(4, 3)

In [5]:
t.size

12

In [6]:
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
t[:, 1]

array([ 2,  5,  8, 11])

In [8]:
m1 = torch.FloatTensor([[3, 3]])

In [9]:
m2 = torch.FloatTensor([[2, 2]])

In [10]:
m1 + m2

tensor([[5., 5.]])

In [11]:
m3 = torch.FloatTensor([[3]])

In [12]:
m1 + m3

tensor([[6., 6.]])

In [13]:
m1 = torch.FloatTensor([[1 ,2]])

In [15]:
m2 = torch.FloatTensor([[3], [4]])

In [16]:
m1 + m2

tensor([[4., 5.],
        [5., 6.]])

In [17]:
a = torch.FloatTensor([[1, 2], [3, 4]])

In [20]:
b = torch.FloatTensor([[1], [2]])

In [21]:
a.matmul(b)

tensor([[ 5.],
        [11.]])

In [22]:
b.matmul(a)

RuntimeError: size mismatch, m1: [2 x 1], m2: [2 x 2] at ..\aten\src\TH/generic/THTensorMath.cpp:41

In [23]:
a.mean()

tensor(2.5000)

In [24]:
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
t.mean()

6.5

In [28]:
t.mean(1)

array([ 2.,  5.,  8., 11.])

In [29]:
t.sum()

78

In [30]:
t.sum(0)

array([22, 26, 30])

In [31]:
t.sum(1)

array([ 6, 15, 24, 33])